docs(i18n-id): Provide Indonesian translation for array-refs, async-components, and attribute coercion
vuejs-id/docs-next pull request #39
Opened 2020-11-09 12:31 UTC by Namchee

## Overview

This is a part of #23 
This pull request provides Indonesian translation for 3 files in `migration` section.

## Changes

`migration`:

- [x] `array-refs.MD`
- [x] `async-components.MD`
- [x] `attribute-coercion.MD`

2020-11-09 12:32 UTC, Namchee commented
Weird, `package-lock.json` shouldn't be included, shall I remove it?

2020-11-09 13:38 UTC, mandaputtra commented
Di hapus saja seharusnya tidak perlu kalau hanya menerjemahkan

2020-11-09 17:38 UTC, mandaputtra requested changes

2020-11-09 17:38 UTC, mandaputtra commented on src/guide/migration/async-components.md
> +Silahkan membaca untuk penjelasan lebih lanjut
```suggestion
Lanjutkan membaca untuk penjelasan lebih lanjut
```

2020-11-09 17:38 UTC, mandaputtra commented on src/guide/migration/attribute-coercion.md
> +### Mengubah `false` menjadi `'false'`
Ada beberapa kata yg belum di terjemahkan

2020-11-10 01:40 UTC, Namchee commented on src/guide/migration/async-components.md
> +Silahkan membaca untuk penjelasan lebih lanjut
Sudah diperbaiki melalui _commit_ fb8f615cfeb48282dfa8e2a8a9370d99dd666b6d

2020-11-10 01:40 UTC, Namchee commented on src/guide/migration/attribute-coercion.md
> +### Mengubah `false` menjadi `'false'`
Kemarin konteksnya agak membingungkan, sehingga saya agak ragu dalam menerjemahkan bagian ini.
Sudah saya perbaiki melalui _commit_ d95524bf99c79d57a24834bb0ee26b2ffe830b11

2020-11-10 02:09 UTC, mandaputtra requested changes
Translasinya sudah bagus, sepertinya `package-lock.json`-nya ngikut kena commit lagi.

2020-11-10 02:21 UTC, mandaputtra approved these changes

2020-11-10 02:23 UTC, merged