docs(i18n-id): Provide Indonesian translation for `migration` - Part 2
vuejs-id/docs-next pull request #50
Opened 2020-11-14 11:58 UTC by Namchee

## Gambaran Umum

_Pull request_ ini merupakan bagian dari #23 
_Pull request_ ini menambahkan terjemahan Bahasa Indonesia untuk beberapa berkas dalam `migration`

### Perubahan

Berikut merupakan berkas yang diterjemahkan

- [x] `attrs-includes-class-style.md`
- [x] `children.md`
- [x] `custom-directives.md`

2020-11-16 02:42 UTC, mandaputtra requested changes
Tolong `package-lock.json`  untuk bisa dihapus? Kalau mau install tanpa merubah package-lock.json bisa gunakan `npm ci`.

Terjemahan sudah oke.

2020-11-17 12:22 UTC, Namchee commented
@mandaputtra `package-lock.json` sudah saya hapus (ter*include* terus-menerus karena saya kebiasaan menggunakan `git add .`). Akankah lebih baik bila _file_ tersebut ditambahkan di `.gitignore`?

2020-11-17 12:30 UTC, mandaputtra commented
Boleh silahkan ditambahkan, lagipula proyek juga menggunakan `yarn`.

2020-11-17 12:45 UTC, mandaputtra approved these changes

2020-11-17 12:45 UTC, merged